import = [
	"~/.config/alacritty/themes/themes/monokai.toml"
]
[font]
normal = {family = "Code New Roman Nerd Font", style = "Regular"}
bold = {family = "Code New Roman Nerd Font", style = "Bold"}
italic = {family = "Code New Roman Nerd Font", style = "Italic"}
bold_italic= {family = "Code New Roman Nerd Font", style = "Bold Italic"}
size= 12.0
